#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#  
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# HOW TO:
# rm -r scripts && git clone https://github.com/alrokayan/scripts.git && cd scripts && chmod +x * && ./k8s-toolkit .env
# OR
# curl -fL -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/alrokayan/scripts/main/k8s-toolkit | bash -s -- .env
# shellcheck disable=SC1090
# shellcheck disable=SC2154
# $1 Enviroment file (optional) (default: .env)
if [ -z "$1" ]; then
  ENV_FILE=".env"
else
  ENV_FILE="$1"
fi
if ! [ -f _include ]; then curl -sfL -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/alrokayan/scripts/main/_include -o _include && chmod +x _include; fi
if ! [ -f "$ENV_FILE" ]; then touch "$ENV_FILE"; fi
mkdir -p tmp
. _include
if ! grep "export SSH_EXTRA_ARGS=" "$ENV_FILE"; then
  echo 'export SSH_EXTRA_ARGS="-o StrictHostKeyChecking=no"' >> "$ENV_FILE"
fi
source "$ENV_FILE"
cat "$ENV_FILE"
if [ -f "$KUBECONFIG" ]; then
  chmod g+r kubeconfig
  chmod go-r kubeconfig
fi
## GENERAL DEFAULT VALUES
NODE_ARRAY_DEFAULT="(10.99.0.100 10.99.0.101 10.99.0.102 10.99.0.103)" && export NODE_ARRAY_DEFAULT
KUBECONFIG_DEFAULT="$(printf "%q\n" "$(pwd)")/kubeconfig" && export KUBECONFIG_DEFAULT
CLUSTER_CIDR_DEFAULT="10.244" && export CLUSTER_CIDR_DEFAULT
L2_SWITCH_DEFAULT="n" && export L2_SWITCH_DEFAULT
MASTER_SCHEDULE_DEFAULT="n" && export MASTER_SCHEDULE_DEFAULT
TZ_DEFAULT="Etc/GMT" && export TZ_DEFAULT
SSH_USERNAME_DEFAULT="root" && export SSH_USERNAME_DEFAULT
PRIVATE_KEY_DEFAULT="$HOME/.ssh/id_rsa" && export PRIVATE_KEY_DEFAULT

#######################################
#######################################
###### FUNCTION copyKubeconfig ########
#######################################
#######################################
function copyKubeconfig() {
  if ! [ -f "$KUBECONFIG" ]; then
    echo "-- Creating $KUBECONFIG"
    for IP in "${NODE_ARRAY[@]}"; do
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
#!/bin/bash
rm -f ~/.kube/config
cp -i /etc/kubernetes/admin.conf ~/.kube/config 
chown "$(id -un)":"$(id -gn)" ~/.kube/config 
chmod g+r ~/.kube/config 
chmod go-r ~/.kube/config 
____EOF____
      rm -f "$KUBECONFIG".BACKUP
      mv "$KUBECONFIG" "$KUBECONFIG".BACKUP
      scp -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP":~/.kube/config "$KUBECONFIG"
      chown "$(id -un)":"$(id -gn)" "$KUBECONFIG"
      chmod g+r "$KUBECONFIG"
      chmod go-r "$KUBECONFIG"
      break
    done
  fi
}

#######################################
#######################################
# FUNCTION createNetworkAttachmentDefinition_STATIC
#######################################
#######################################
function createNetworkAttachmentDefinition_STATIC() {
  cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: $BRIDGE_NAME
  namespace: $APP_NAMESPACE
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "$BRIDGE_NAME",
      "plugins": [
        {
          "cniVersion": "1.0.0",
          "type": "macvlan",
          "mode": "bridge",
          "mac": "$MAC",
          "master": "$MASTER_NIC",
          "isDefaultGateway": true,
          "enableIPv6": false,
          "ipam": {
            "type": "static",
            "addresses":
            [
              {
                "address": "$IPCIDR", 
                "gateway": "$GW"
              }
            ],
            "routes":
            [
              {
                "dst": "0.0.0.0/0"
              }
            ]
          },
          "dns":
          {
            "nameservers":
            [
              "$DNS1",
              "$DNS2" 
            ]
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "snat": true
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
EOF
}

#######################################
#######################################
# FUNCTION createNetworkAttachmentDefinition_DHCP
#######################################
#######################################
function createNetworkAttachmentDefinition_DHCP() {
  cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: $BRIDGE_NAME
  namespace: $APP_NAMESPACE
spec:
  config: '{
      "cniVersion": "1.0.0",
      "name": "$BRIDGE_NAME",
      "plugins": [
        {
          "cniVersion": "1.0.0",
          "type": "macvlan",
          "mode": "bridge",
          "mac": "$MAC",
          "master": "$MASTER_NIC",
          "isDefaultGateway": true,
          "enableIPv6": false,
          "ipam": {
            "type": "dhcp",
            "routes":
            [
              {
                "dst": "0.0.0.0/0"
              }
            ],
            "daemonSocketPath": "/run/cni/dhcp.sock",
            "request": [
              {
                  "skipDefault": false
              }
            ],
            "provide": [
              {
                "option": "host-name",
                "fromArg": "k8s-$APP_NAMESPACE"
              }
            ]
          },
          "dns":
          {
            "nameservers":
            [
              "$DNS1",
              "$DNS2"
            ]
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "snat": true
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
EOF
}

#######################################
#######################################
###### FUNCTION SWAPRemoval ###########
#######################################
#######################################
function SWAPRemoval() {
  echo "-- Removing SWAP and rebooting if needed on all nodes" 
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" "bash -s" <<'____EOF____'
#!/bin/bash
if free | awk '/^Swap:/ {exit !$2}'; then
  echo "-- NODE $i -- removing swap partition "
  sed -e '/swap/ s/^#*/#/' -i /etc/fstab
  umount /swap.img
  rm -f /swap.img
  swapoff -a
  reboot
fi
____EOF____
    ) &
  done
  wait
  WAIT_ALL_NODES_ONLINE "${NODE_ARRAY[@]}"
}

#######################################
#######################################
####### FUNCTION runDNSTool ###########
#######################################
#######################################
function runDNSTool() {
  readVar app_dnstools_master_nic "eth0" "Please entre master NIC for dnstools (run \"ip a\" in ${#NODE_ARRAY[0]} to get all available NICs)" 1
  readVar app_dnstools_mac "$(printf '00:2F:60:%02X:%02X:%02X\n' "$(shuf -i 0-99 -n 1)" "$(shuf -i 101-199 -n 1)" "$(shuf -i 201-256 -n 1)")" "Please entre the MAC address for this NIC" 1
  readVar app_dnstools_ip "" "Please entre the IP address for dnstools with subnet suffex (example: 10.99.0.60/24). Leave empty for DHCP" 1
  export MASTER_NIC="$app_dnstools_master_nic"
  export BRIDGE_NAME="cbr-$app_dnstools_master_nic"
  export APP_NAMESPACE="app-dnstools"
  export MAC="$app_dnstools_mac"
  echo "-- Creating $APP_NAMESPACE namespace"
  kubectl create ns $APP_NAMESPACE
  kubectl delete network-attachment-definitions.k8s.cni.cncf.io "$BRIDGE_NAME" -n "$APP_NAMESPACE"
  if [ "$app_dnstools_ip" != "" ]; then
    readVar app_dnstools_gw "10.99.0.1" "Please entre the gateway address for dnstools" 1
    echo "-- Deploying cbr1-$app_dnstools_master_nic NetworkAttachmentDefinition" 
    export IPCIDR="$app_dnstools_ip"
    export GW="$app_dnstools_gw"
    createNetworkAttachmentDefinition_STATIC
  else
    echo "-- Deploying cbr2-$app_dnstools_master_nic NetworkAttachmentDefinition" 
    createNetworkAttachmentDefinition_DHCP
  fi
  echo "-- Running dnstools pod" 
  kubectl run -it --rm \
    --namespace $APP_NAMESPACE \
    --restart=Never \
    --image=infoblox/dnstools:latest \
    --annotations="'k8s.v1.cni.cncf.io/networks=$BRIDGE_NAME'" \
    dnstools 
  echo "-- Deleting $APP_NAMESPACE namespace" 
  kubectl delete ns $APP_NAMESPACE --grace-period=0 --force
}

#######################################
#######################################
######### FUNCTION binInstall #########
#######################################
#######################################
function binInstall() {
  force_install_bin=$1
  if [[ "$(uname -s)" == *"Linux"* ]]; then
    if $force_install_bin; then
      echo "-- OS: Linux - DOWNLOADING BINARIES" 
    else
      echo "-- OS: Linux - CHECKING BINARIES" 
    fi
    if ! command -v helm &> /dev/null || $force_install_bin; then
      rm -rf tmp/helm.tar.gz tmp/linux-"$(dpkg --print-architecture)"
      curl -L https://get.helm.sh/helm-v3.15.2-linux-"$(dpkg --print-architecture)".tar.gz -o tmp/helm.tar.gz
      tar -zxf tmp/helm.tar.gz -C tmp
      sudo rm -f /usr/local/bin/helm
      sudo mv tmp/linux-"$(dpkg --print-architecture)"/helm /usr/local/bin/
      sudo chmod +x /usr/local/bin
      if command -v helm &> /dev/null; then echo "-- helm installed successfully" ; fi
    fi
    if ! command -v kubectl &> /dev/null || $force_install_bin; then
      sudo rm -f /usr/local/bin/kubectl
      sudo curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/$(dpkg --print-architecture)/kubectl" -o /usr/local/bin/kubectl
      sudo chmod +x /usr/local/bin/kubectl
      if command -v kubectl &> /dev/null; then echo "-- kubectl installed successfully" ; fi
    fi
    if ! command -v jq &> /dev/null || $force_install_bin; then
      sudo rm -f /usr/local/bin/jq
      sudo curl -L "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-$(dpkg --print-architecture)" -o /usr/local/bin/jq
      sudo chmod +x /usr/local/bin/jq
      if command -v jq &> /dev/null; then echo "-- jq installed successfully" ; fi
    fi
    if ! command -v k9s &> /dev/null || $force_install_bin; then
      rm -rf tmp/k9s.tar.gz tmp/k9s
      curl -L https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Linux_"$(dpkg --print-architecture)".tar.gz -o tmp/k9s.tar.gz
      mkdir tmp/k9s
      tar -zxf tmp/k9s.tar.gz -C tmp/k9s
      sudo rm -f /usr/local/bin/k9s
      sudo mv tmp/k9s/k9s /usr/local/bin/
      sudo chmod +x /usr/local/bin/k9s
      if command -v k9s &> /dev/null; then echo "-- k9s installed successfully" ; fi
    fi
  fi
  if [[ "$(uname -s)" == *"Darwin"* ]]; then
    if $force_install_bin; then
      echo "-- OS: macOS - DOWNLOADING BINARIES" 
    else
      echo "-- OS: macOS - CHECKING BINARIES" 
    fi
    if ! command -v helm &> /dev/null || $force_install_bin; then
      rm -rf tmp/helm.tar.gz tmp/linux-"$(dpkg --print-architecture)"
      curl -L "https://get.helm.sh/helm-v3.15.2-darwin-$(arch).tar.gz" -o tmp/helm.tar.gz
      tar -zxf tmp/helm.tar.gz -C tmp
      sudo rm -f /usr/local/bin/helm
      sudo mv tmp/darwin-"$(arch)"/helm /usr/local/bin/
      sudo chmod +x /usr/local/bin/helm
      if command -v helm &> /dev/null; then echo "-- helm installed successfully" ; fi
    fi
    if ! command -v kubectl &> /dev/null || $force_install_bin; then
      sudo rm -f /usr/local/bin/kubectl
      sudo curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/darwin/$(arch)/kubectl" -o /usr/local/bin/kubectl
      sudo chmod +x /usr/local/bin/kubectl
      if command -v kubectl &> /dev/null; then echo "-- kubectl installed successfully" ; fi
    fi
    if ! command -v jq &> /dev/null || $force_install_bin; then
      sudo rm -f /usr/local/bin/jq
      sudo curl -L "https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-macos-$(arch)" -o /usr/local/bin/jq
      sudo chmod +x /usr/local/bin/jq
      if command -v jq &> /dev/null; then echo "-- jq installed successfully" ; fi
    fi
    if ! command -v k9s &> /dev/null || $force_install_bin; then
      rm -rf tmp/k9s.tar.gz tmp/k9s
      curl -L "https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_Darwin_$(arch).tar.gz" -o tmp/k9s.tar.gz
      mkdir tmp/k9s
      tar -zxf tmp/k9s.tar.gz -C tmp/k9s
      sudo rm -f /usr/local/bin/k9s
      sudo mv tmp/k9s/k9s /usr/local/bin/
      sudo chmod +x /usr/local/bin/k9s
      if command -v k9s &> /dev/null; then echo "-- k9s installed successfully" ; fi
    fi
  fi
}
#######################################
#######################################
####### FUNCTION FixFlannel ###########
#######################################
#######################################
function FixFlannel() {
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" "bash -s" <<'____EOF____'
#!/bin/bash
for nic in $(ip link show | grep -e ": cni" -e ": flannel" | awk -F@ '{print $1}' | awk '{print $2}'); do
  ip link set $nic down
  ip link delete $nic
done
systemctl restart containerd 
systemctl restart kubelet 
____EOF____
    ) &
  done
  wait
}

#######################################
#######################################
######### FUNCTION setDNS1 ############
#######################################
#######################################
function setDNS1() {
  CORE_DNS_POD_NAME1=$(kubectl get pod -l k8s-app=kube-dns -n kube-system --no-headers=true | awk 'NR==1{print $1}')
  CORE_DNS_DNS1=$(kubectl get pod "$CORE_DNS_POD_NAME1" -n kube-system --template '{{.status.podIP}}')
}

#######################################
#######################################
######### FUNCTION setDNS2 ############
#######################################
#######################################
function setDNS2() {
  CORE_DNS_POD_NAME2=$(kubectl get pod -l k8s-app=kube-dns -n kube-system --no-headers=true | awk 'NR==2{print $1}')
  CORE_DNS_DNS2=$(kubectl get pod "$CORE_DNS_POD_NAME2" -n kube-system --template '{{.status.podIP}}')
}

#######################################
#######################################
######### FUNCTION FixDNS #############
#######################################
#######################################
function FixDNS() {
  echo "-- Fixing CoreDNS IP addresses in kubelet config " 
  setDNS1
  setDNS2
  echo "-- CoreDNS IP1: $CORE_DNS_DNS1" 
  echo "-- CoreDNS IP2: $CORE_DNS_DNS2" 
  for IP in "${NODE_ARRAY[@]}"; do
    ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" i="$i" CORE_DNS_DNS1="$CORE_DNS_DNS1" CORE_DNS_DNS2="$CORE_DNS_DNS2" "bash -s" <<'____EOF____'
#!/bin/bash
if [ "$CORE_DNS_DNS1" != "<no value>" ]; then
  mkdir -p /var/lib/kubelet/kubeletconfigurationpatches
  if [ "$CORE_DNS_DNS2" != "<no value>" ]; then
    echo "clusterDNS:
- $CORE_DNS_DNS1
- $CORE_DNS_DNS2
clusterDomain: cluster.local
resolvConf: /etc/resolv.conf" > '/var/lib/kubelet/kubeletconfigurationpatches/kubeletconfiguration0+merge.yaml'
  else
    echo "clusterDNS:
- $CORE_DNS_DNS1
clusterDomain: cluster.local
resolvConf: /etc/resolv.conf" > '/var/lib/kubelet/kubeletconfigurationpatches/kubeletconfiguration0+merge.yaml'
  fi
fi
echo "-- $HOSTNAME: Upgrading kubelet configuration"
kubeadm upgrade node phase kubelet-config --patches /var/lib/kubelet/kubeletconfigurationpatches/
____EOF____
    break
  done
}
#######################################
#######################################
############ FUNCTION unDeploy ########
#######################################
#######################################
function unDeploy() {
  NSLIST="$(kubectl get namespaces -o name | grep -v kube- | cut -c 11-)"
    for ns in $NSLIST; do
      echo "-- Uninstalling all resources in $ns " 
      (
        helm ls --all --short -n "$ns" | xargs -L1 helm delete -n "$ns"
        kubectl delete all --all --namespace="$ns" --grace-period=0 --force
        if [ "$ns" != "default" ]; then
          kubectl delete ns "$ns" --grace-period=0 --force
        fi
      ) &
    done
}

#######################################
#######################################
############ FUNCTION unDeployAll #####
#######################################
#######################################
function unDeployAll() {
  echo "-- apps and kube-network uninstall"
  unDeploy
  echo "-- Uninstalling Multus" 
  (
  if ! [ -f tmp/multus-daemonset-thick.yml ]; then
    curl --silent -fsSL https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml -o tmp/multus-daemonset-thick.yml
    sed -i.BACKUP 's/namespace: kube-system/namespace: kube-network/g' tmp/multus-daemonset-thick.yml
  fi
  kubectl delete -n kube-network -f tmp/multus-daemonset-thick.yml --grace-period=0 --force
  ) &
  echo "-- Uninstalling DHCP" 
  (
  if ! [ -f tmp/dhcp-daemonset.yml ]; then
    curl --silent -fsSL https://raw.githubusercontent.com/k8snetworkplumbingwg/reference-deployment/master/multus-dhcp/dhcp-daemonset.yml -o tmp/dhcp-daemonset.yml
    sed -i.BACKUP 's/namespace: kube-system/namespace: kube-network/g' tmp/dhcp-daemonset.yml
  fi
  kubectl delete -n kube-network -f tmp/dhcp-daemonset.yml --grace-period=0 --force
  ) &
  echo "-- Uninstalling flannel" 
  ( helm uninstall flannel -n kube-network ) &
  echo "-- Uninstalling all resources in kube-network " 
  (
    helm ls --all --short -n "kube-network" | xargs -L1 helm delete -n "kube-network"
    kubectl delete all --all --namespace="$ns" --grace-period=0 --force
    kubectl delete ns "kube-network" --grace-period=0 --force
  ) &
  wait & sleep 10
  echo "-- Deleting leftover NICs, and cni files on all nodes" 
  for IP in "${NODE_ARRAY[@]}"; do
    (
    ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" bash <<'____EOF____'
#!/bin/bash
echo "-- $HOSTNAME: deleting leftover NICs"
for nic in $(ip link show | grep -e ": cni" -e ": flannel" | awk -F@ '{print $1}' | awk '{print $2}'); do
  ip link set $nic down
  ip link delete $nic
done
echo "-- $HOSTNAME: Force stopping cni demon"
kill -9 $(ps aux | grep -v "grep" | grep -e "/opt/cni/bin" | awk '{print $2}')
echo "-- $HOSTNAME: Deleting cni files"
rm -rf /run/flannel
rm -rf /opt/cni
rm -rf /run/cni
rm -rf /var/lib/cni
rm -rf /etc/cni
____EOF____
    ) &
  done
  wait & sleep 10
  echo "-- Restarting CoreDNS" 
  kubectl delete pod --selector=k8s-app=kube-dns -n kube-system --grace-period=0 --force
  echo "-- Uninstalling Network-Attachment-Definitions" 
  kubectl delete Network-Attachment-Definitions --all -A --grace-period=0 --force
}

#######################################
#######################################
############ FUNCTION unDeployApps ####
#######################################
#######################################
function unDeployApps() {
  echo "-- apps uninstall" 
  unDeploy
  wait & sleep 10
  echo "-- Uninstalling Network-Attachment-Definitions" 
  kubectl delete Network-Attachment-Definitions --all -A --grace-period=0 --force
}

#######################################
#######################################
####### FUNCTION END_OF_SCRIPT ########
#######################################
#######################################
function END_OF_SCRIPT() {
  if $CONTINUE; then
    echo "-------------------------------------------------------------" 
    echo "👍 Script executed successfully. Press any key to continue .." 
    echo "-------------------------------------------------------------" 
    read -r
  fi
}

#######################################
#######################################
###### FUNCTION step0 1 2 3 4 5 #######
#######################################
#######################################
function step0() {
  binInstall false
  copyKubeconfig
  SWAPRemoval
  for IP in "${NODE_ARRAY[@]}"; do
    response="$(curl -w '%{http_code}' -o /dev/null -ILks "https://$IP:6443")"
    break
  done
  if [[ "$response" != *"000"* ]]; then
    unDeployAll
    for i in $(kubectl get nodes -o name | cut -c 6-); do
      echo "-- Draining and deleting $i" 
      kubectl drain "$i" --force --grace-period=0
      kubectl delete node "$i" --all --force --grace-period=0
    done
  fi

  echo "-- Uninstalling (reset kubeadm, firewall, files, network) on all nodes" 
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" "bash -s" <<'____EOF____'
#!/bin/bash

echo "-- $HOSTNAME: Uninstalling"
if command -v kubeadm &> /dev/null; then
    echo "-- $HOSTNAME: Resting k8s"
    kubeadm reset --cleanup-tmp-dir --force 
fi
echo "-- $HOSTNAME: Uninstalling k8s (kubelet, kubeadm, and containerd)"
systemctl stop $(systemctl -l | grep kube) 
systemctl disable $(systemctl -l | grep kube) 
apt-mark unhold kubelet kubeadm kubectl docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin 
for pkg in kubectl kubeadm kubelet docker-ce docker-ce-cli docker.io containerd.io docker-doc docker-build-plugin docker-compose-plugin docker-compose docker-compose-v2 podman-docker containerd runc containerd; do
    apt purge -y --allow-change-held-packages $pkg 
done
echo "-- $HOSTNAME: Removing gpg and source lists of kubernetes and adoptium"
rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
rm -f /etc/apt/trusted.gpg.d/adoptium.gpg
rm -f /etc/apt/sources.list.d/kubernetes.list
rm -f /etc/apt/sources.list.d/adoptium.list
apt update -y
echo "-- $HOSTNAME: Unmounting and deleting containerd, kubelet, cni, etcd and other kubernetes files and folders"
umount -f /var/run/containerd/*/*/*/* 
umount -f /var/lib/kubelet/*/*/*/*/* 
rm -rf /opt/containerd
rm -rf /var/lib/containerd
rm -rf /var/lib/kubelet
rm -rf /var/run/containerd
rm -rf ~/.kube
rm -rf /etc/kubernetes
rm -rf /var/lib/etcd
rm -f /run/flannel/subnet.env
rm -rf /opt/cni
rm -rf /run/cni
rm -rf /var/lib/cni
rm -rf /etc/cni
rm -f /etc/apt/trusted.gpg.d/adoptium.gpg
rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
rm -f /etc/apt/sources.list.d/kubernetes.list
rm -f /etc/apt/sources.list.d/adoptium.list
rm -rf /usr/libexec/kubernetes
rm -rf /var/log/containers
rm -rf /.kube
rm -f /root/kubeletconfiguration0+merge.yaml
rm -rf /tmp/*-save.txt
rm -f /etc/modules-load.d/kubernetes.conf
rm -f /etc/sysctl.d/98-kubernetes.conf
sysctl --system 
sed -i '/.*DNSStubListener=no.*/ c\#DNSStubListener=' /etc/systemd/resolved.conf
echo "-- $HOSTNAME: apt update autoremove autoclean"
apt update -y
apt autoremove -y --purge 
apt autoclean -y 
apt clean -y 
echo "-- $HOSTNAME: deleting leftover NICs"
for nic in $(ip link show | grep -e ": lxc" -e ": cali" -e ": cilium" -e ": flannel" -e ": tunl" -e ": cni" -e ": cbr" | awk -F@ '{print $1}' | awk '{print $2}'); do
  ip link set $nic down
  ip link delete $nic
done
echo "-- $HOSTNAME: Uninstall Completed"
____EOF____
    ) &
  done
  wait
  echo "---------------------------------------------------------------" 
}

##################################################################################
##################################################################################
function step1() {
  echo "-- Creating and copying hosts file" 
  echo "127.0.0.1 localhost" >tmp/hosts
  for IP in "${NODE_ARRAY[@]}"; do
    NODE_HOSTNAME=$(ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" "hostname")
    echo "$IP $NODE_HOSTNAME" >>tmp/hosts
  done
  echo '
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters' >>tmp/hosts
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" "mv /etc/hosts /etc/hosts.BACKUP"
      scp -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" tmp/hosts "$SSH_USERNAME"@"$IP":/etc/
    ) &
  done
  wait

  echo "-- Updating, upgrading and installing pre-requisites on all nodes, please wait ..." 
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" "bash -s" <<'____EOF____'
#!/bin/bash
echo "-- $HOSTNAME: Creating folders and setting permissions"
mkdir -p ~/.kube
mkdir -p /opt/cni/bin
mkdir -p /run/cni
mkdir -p /etc/cni/net.d
mkdir -p /etc/containerd
chown -R "$(id -un)":"$(id -gn)" /opt/cni
chown -R "$(id -un)":"$(id -gn)" /etc/cni
chown -R "$(id -un)":"$(id -gn)" /etc/containerd
chown -R "$(id -un)":"$(id -gn)" /run/cni
chmod -R +r /opt/cni/bin
echo "-- $HOSTNAME: Disabling iptables"
for cmd in iptables ip6tables iptables-legacy ip6tables-legacy; do
  $cmd-save > /tmp/$cmd-save.txt 
  $cmd -P INPUT ACCEPT 
  $cmd -P FORWARD ACCEPT 
  $cmd -P OUTPUT ACCEPT 
  $cmd -t nat -F 
  $cmd -t nat -X 
  $cmd -t mangle -F 
  $cmd -t mangle -X 
  $cmd -F 
  $cmd -X 
done
update-alternatives --remove iptables /usr/sbin/iptables-legacy
echo "-- $HOSTNAME: Updating, upgrading and installing pre-requisites, please wait ..."
apt update -y 
apt upgrade -y 
apt install -y \
    apt-transport-https \
    ca-certificates \
    nfs-common \
    curl \
    gpg \
    sudo \
    wget \
    gnupg \
    util-linux \
    coreutils \
    git \
    nano \
    cifs-utils 
echo "-- $HOSTNAME: Enabling kernel modules, ip forwarding and disabling DNSStubListener"
echo 'overlay
br_netfilter' > /etc/modules-load.d/kubernetes.conf
modprobe overlay
modprobe br_netfilter
echo 'net.bridge.bridge-nf-call-iptables=1
net.bridge.bridge-nf-call-ip6tables=1
net.bridge.bridge-nf-call-arptables=1
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1' > /etc/sysctl.d/98-kubernetes.conf
sed -i '/#DefaultTimeoutStopSec=90s/c\DefaultTimeoutStopSec=10s' /etc/systemd/system.conf
sed -i 's/GRUB_CMDLINE_LINUX_DEFAULT=\"/&usbcore.autosuspend=-1 /' /etc/default/grub
sed -i '/.*#DNSStubListener=.*/ c\DNSStubListener=no' /etc/systemd/resolved.conf
update-grub 
sysctl --system 
echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
apt-get install -y -q
echo "-- $HOSTNAME: Installing gpg for jave (adoptium) and kubernetes"
mkdir -p -m 755 /etc/apt/keyrings
mkdir -p /etc/apt/sources.list.d/
mkdir -p /etc/apt/trusted.gpg.d/
apt update -y 
# kubernetes
curl --silent -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --batch --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg 
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' > /etc/apt/sources.list.d/kubernetes.list 
# adoptium
curl --silent -fsSL https://packages.adoptium.net/artifactory/api/gpg/key/public | gpg --batch --yes --dearmor -o /etc/apt/trusted.gpg.d/adoptium.gpg
echo "deb https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" > /etc/apt/sources.list.d/adoptium.list
apt update -y 
echo "-- $HOSTNAME: Installing Jave"
apt install -y temurin-21-jre 
echo "-- $HOSTNAME: Installing containerd"
apt install -y containerd
____EOF____
    ) &
  done
  wait

  if [ "$K8S_VERSION" == "" ]; then
    for IP in "${NODE_ARRAY[@]}"; do
      DEFAULT_VERSION=$(ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" "apt-cache policy kubeadm | grep Candidate | awk '{print \$2}'")
      break
    done
    readVar K8S_VERSION "$DEFAULT_VERSION" "Please entre k8s version" 1 30
  fi
  echo "-- Installing kubernetes (version: $K8S_VERSION) on all nodes" 
  for IP in "${NODE_ARRAY[@]}"; do
    (
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" K8S_VERSION="$K8S_VERSION" "bash -s" <<'____EOF____'
#!/bin/bash
echo "-- $HOSTNAME: Installing kubernetes (version: $K8S_VERSION)"
apt install -y --allow-change-held-packages kubelet=$K8S_VERSION kubeadm=$K8S_VERSION kubectl=$K8S_VERSION 
apt-mark hold kubelet kubeadm kubectl containerd  
sh -c "containerd config default > /etc/containerd/config.toml"  
sed -i 's/ SystemdCgroup = false/ SystemdCgroup = true/' /etc/containerd/config.toml
systemctl daemon-reload 
systemctl enable --now kubelet.service
systemctl enable --now containerd.service
echo "-- $HOSTNAME: Pulling kubernetes images"
kubeadm config images pull --kubernetes-version $(echo "$K8S_VERSION" | sed 's/-[0-9].*//')
____EOF____
    ) &
  done
  wait
  echo "---------------------------------------------------------------" 
}

##################################################################################
##################################################################################
function step2() {
  echo "-- Initializing kubernetes version: ${K8S_VERSION//-[0-9].*/}"
  for IP in "${NODE_ARRAY[@]}"; do
    ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" CLUSTER_CIDR_FIRST_TWO_OCTETS="$CLUSTER_CIDR_FIRST_TWO_OCTETS" MASTER_IP="$IP" K8S_VERSION="$K8S_VERSION" SSH_USERNAME="$SSH_USERNAME" "bash -s" <<'____EOF____'
#!/bin/bash
echo "-- $HOSTNAME: Initializing k8s master version: $(echo "$K8S_VERSION" | sed 's/-[0-9].*//')"
kubeadm init  --kubernetes-version $(echo "$K8S_VERSION" | sed 's/-[0-9].*//') \
              --apiserver-advertise-address=$MASTER_IP \
              --pod-network-cidr=${CLUSTER_CIDR_FIRST_TWO_OCTETS}.0.0/16
echo "-- $HOSTNAME: Creating join.sh"
kubeadm token create --print-join-command > ~/.kube/join.sh
echo "-- $HOSTNAME: Auto kill stuck failed pods every 10 minutes"
cat <<'EOF' >/etc/systemd/system/kill-failed-pods
#!/bin/bash
while true; do
  for ns in $(kubectl --kubeconfig "/etc/kubernetes/admin.conf" get namespaces -o name | cut -c 11-); do
    for pod in $(kubectl --kubeconfig "/etc/kubernetes/admin.conf" get pods -n "$ns" -o go-template="{{ range  \$item := .items }}{{ range .status.conditions }}{{ if (or (and (eq .type \"PodScheduled\") (eq .status \"False\")) (and (eq .type \"Ready\") (eq .status \"False\"))) }}{{ \$item.metadata.name}} {{ end }}{{ end }}{{ end }}"); do
        kubectl --kubeconfig "/etc/kubernetes/admin.conf" delete pods -n "$ns" "$pod" --grace-period=0 --force
    done
  done
  sleep 600
done
EOF
chmod +x /etc/systemd/system/kill-failed-pods
cat <<EOF >/lib/systemd/system/kill-failed-pods.service
[Unit]
Description=kill-failed-pods

[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/etc/systemd/system/kill-failed-pods

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now kill-failed-pods
____EOF____
    break
  done
  echo "-- Copying kubeconfig" 
  rm -f "$KUBECONFIG"
  copyKubeconfig
  echo "-- Copying kubeconfig to all nodes" 
  for IP in "${NODE_ARRAY[@]}"; do
    (scp -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$KUBECONFIG" "$SSH_USERNAME"@"$IP":~/.kube/config) &
  done
  wait
  echo "-- Copying join command file to this machine" 
  IS_MASTER=true
  for IP in "${NODE_ARRAY[@]}"; do
    if $IS_MASTER; then
      IS_MASTER=false
      rm -f tmp/join.sh
      scp -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP":~/.kube/join.sh tmp/
      chmod +x tmp/join.sh
    else
      echo "-- $IP joining the cluster" 
      scp -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" tmp/join.sh "$SSH_USERNAME"@"$IP":~/.kube/join.sh
      (
        ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" DEBIAN_FRONTEND="noninteractive" i="$i" "bash -s" <<'____EOF____'
#!/bin/bash
chmod +x $HOME/.kube/join.sh
echo "-- $HOSTNAME: Joining k8s cluster"
$HOME/.kube/join.sh
echo "-- $HOSTNAME: Completed"
____EOF____
      ) &
    fi
  done
  wait  
  echo "---------------------------------------------------------------" 
}

##################################################################################
##################################################################################
function step3() {
  copyKubeconfig
  echo "-- Adding helm repos" 
  helm repo add flannel https://flannel-io.github.io/flannel/
  helm repo add bitnami https://charts.bitnami.com/bitnami
  helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
  echo "-- Updating helm repos" 
  helm repo update
  if [ -f "$KUBECONFIG" ]; then
    ## Allow master node to schedule pods
    if [ ${#NODE_ARRAY[@]} -eq 1 ] || [ "$MASTER_SCHEDULE" == "y" ]; then
      echo "-- Allowing master node to schedule app ..." 
      MASTER_HOSTNAME=$(ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"${NODE_ARRAY[0]}" hostname)
      kubectl taint nodes "$MASTER_HOSTNAME" node-role.kubernetes.io/control-plane:NoSchedule-
    fi
    ## Create namespaces
    echo "-- Creating kube-network namespaces" 
    kubectl create ns kube-network
    kubectl label --overwrite ns kube-network pod-security.kubernetes.io/enforce=privileged
    echo "-- Creating subnet.env and downloading cni binaries on all nodes" 
    i=0
    for IP in "${NODE_ARRAY[@]}"; do
      ssh -i "$PRIVATE_KEY" "$SSH_EXTRA_ARGS" "$SSH_USERNAME"@"$IP" CLUSTER_CIDR_FIRST_TWO_OCTETS="$CLUSTER_CIDR_FIRST_TWO_OCTETS" i="$i" bash <<'____EOF____'
#!/bin/bash
echo "-- $HOSTNAME: Creating subnet.env"
mkdir -p /run/flannel
rm -f /run/flannel/subnet.env
cat << EOF > /run/flannel/subnet.env
FLANNEL_NETWORK=${CLUSTER_CIDR_FIRST_TWO_OCTETS}.0.0/16
FLANNEL_SUBNET=${CLUSTER_CIDR_FIRST_TWO_OCTETS}.$i.0/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
EOF
echo "-- $HOSTNAME: Downloading CNI binaries cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)-v1.5.0.tgz"
mkdir -p /opt/cni/bin
curl -s -L "https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-$( [ $(uname -m) = aarch64 ] && echo arm64 || echo amd64)"-v1.5.0.tgz | tar xzf - -C /opt/cni/bin
chown -R "$(id -un)":"$(id -gn)" /opt/cni
____EOF____
      i=$((i + 1))
    done
    wait
    if [ "$L2_SWITCH" == "y" ]; then
      FLANNEL_BACKEND="host-gw"
    else
      FLANNEL_BACKEND="vxlan"
    fi
    echo "-- Deploying flannel with backend $FLANNEL_BACKEND" 
    # https://github.com/flannel-io/flannel/blob/master/chart/kube-flannel/values.yaml
    helm upgrade --install flannel \
      --namespace kube-network --create-namespace \
      --set podCidr="${CLUSTER_CIDR_FIRST_TWO_OCTETS}.0.0/16" \
      --set flannel.backend="$FLANNEL_BACKEND" \
      flannel/flannel
    echo "-- Deploying Multus" 
    rm -f tmp/multus-daemonset-thick.yml
    curl --silent -fsSL https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick.yml -o tmp/multus-daemonset-thick.yml
    sed -i.BACKUP 's/namespace: kube-system/namespace: kube-network/g' tmp/multus-daemonset-thick.yml
    kubectl apply -n kube-network -f tmp/multus-daemonset-thick.yml
    echo "-- Deploying DHCP CNI plugin" 
    curl --silent -fsSL https://raw.githubusercontent.com/k8snetworkplumbingwg/reference-deployment/master/multus-dhcp/dhcp-daemonset.yml -o tmp/dhcp-daemonset.yml
    sed -i.BACKUP 's/namespace: kube-system/namespace: kube-network/g' tmp/dhcp-daemonset.yml
    kubectl apply -n kube-network -f tmp/dhcp-daemonset.yml
    wait
    sleep 5
    echo "-- Restarting CoreDNS" 
    kubectl delete pod --selector=k8s-app=kube-dns -n kube-system --grace-period=0 --force
    echo "-- waiting for flannel" 
    while [ "$(kubectl get pods -A -l app=flannel -ojson | jq '.items[0].status.phase')" != "\"Running\"" ]; do
      FixFlannel
      sleep 20
    done
    sleep 5
    if [ "$(kubectl get pods -n kube-system -l k8s-app=kube-dns -ojson | jq '.items[0].status.phase')" != "\"Running\"" ]; then
      kubectl delete pod --selector=k8s-app=kube-dns -n kube-system --force
      echo "-- waiting for CoreDNS" 
      while [ "$(kubectl get pods -n kube-system -l k8s-app=kube-dns -ojson | jq '.items[0].status.phase')" != "\"Running\"" ]; do
        FixFlannel
        sleep 20
      done
    fi
    sleep 5
    FixDNS
    echo "-- Installing prometheus-operator and metrics-server" 
    # DEFAULT VALUES: https://github.com/truecharts/charts/blob/master/charts/system/prometheus-operator/values.yaml
    ( helm upgrade --install prometheus-operator oci://tccr.io/truecharts/prometheus-operator --namespace=kube-network &> /dev/null ) &
    # DEFAULT VALUES: https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
    ( helm upgrade --install metrics-server metrics-server/metrics-server --set args="{--kubelet-insecure-tls,--kubelet-preferred-address-types=InternalIP,--cert-dir=/tmp}" --set apiService.insecureSkipTLSVerify=true --namespace=kube-network &> /dev/null ) &
  else
    echo "Please do step 2 before kubernetes cluster is not installed .." 
  fi
  echo "---------------------------------------------------------------" 
}

##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
##################################################################################
echo "---------------------------------------------------------------" 
echo "------------------------- K8S TOOLKIT -------------------------" 
echo "---------------------------------------------------------------" 
echo "LOG FILE: $LOG_FILE" 
echo "KUBECONFIG: $KUBECONFIG" 
echo "SSH KEYS: $PRIVATE_KEY"  
echo "kubectl bin: $(which kubectl)"  
echo "---------------------------------------------------------------" 
if [ -z "${NODE_ARRAY[0]}" ] || [ -z "$SSH_USERNAME" ] || [ -z "$PRIVATE_KEY" ] || [ -z "$KUBECONFIG" ] || [ -z "$CLUSTER_CIDR_FIRST_TWO_OCTETS" ] || [ -z "$KUBE_TZ" ] || [ -z "$MASTER_SCHEDULE" ] || [ -z "$L2_SWITCH" ]; then
  echo "Please answer the following questions to create the environment" 
  echo "---------------------------------------------------------------" 
fi
while ! IS_ALL_NODES_ONLINE "$NODE_ARRAY"; do
  source "$ENV_FILE"
  readArrayVar NODE_ARRAY "Please entre kubernetes cluster's nodes IP addresses the first one is the master (separate IPs with SPACE)" "$(IFS=' ' ; echo "$NODE_ARRAY_DEFAULT" )"
  source "$ENV_FILE"
done
readVar SSH_USERNAME "$SSH_USERNAME_DEFAULT" "Please entre the SSH username" 1
while ! SSH_COPY_ID "$PRIVATE_KEY" "$(IFS=' ' ; echo "$NODE_ARRAY" )" || [ ! -f "$PRIVATE_KEY" ]; do
  PRIVATE_KEY="$PRIVATE_KEY_DEFAULT"
  readVar PRIVATE_KEY "$PRIVATE_KEY_DEFAULT" "Please enter the absolute path for your private key. The default value is recommended (will be created if it does not exist)"
done
readYesNoVar L2_SWITCH "$L2_SWITCH_DEFAULT" "Are all nodes connected to a L2 switch? (entre y or n)" 1
readYesNoVar MASTER_SCHEDULE "$MASTER_SCHEDULE_DEFAULT" "Do you want to schedule pods in the master node? (entre y or n)" 1
if [ ! -f "$KUBECONFIG" ]; then
  readVar KUBECONFIG "$KUBECONFIG_DEFAULT" "Please entre the path for KUBECONFIG (will be created if it does not exist)"
fi
readVar CLUSTER_CIDR_FIRST_TWO_OCTETS "$CLUSTER_CIDR_DEFAULT" "Please entre the first two octets of the subnet 16 of the cluster CIDR (10.244 means 10.244.0.0/16)" 1
readVar KUBE_TZ "$TZ_DEFAULT" "Please entre your Time Zone" 1

##############################################################################################################
binInstall false
CONTINUE=true
while $CONTINUE; do
  source "$ENV_FILE"
  if [ "$2" == "" ]; then
    echo "-----------------------------------------------------------" 
    echo "Welcome to K8S TOOLKIT .." 
    echo "-----------------------------------------------------------" 
    echo "(q)    < Quit (and remove tmp and logs folders)" 
    echo "-----------------------------------------------------------" 
    echo "------------------- INSTALLATION STEPS --------------------" 
    echo "-----------------------------------------------------------" 
    echo "[0].....Uninstall Everything" 
    echo "[1].....Prepare hosts and install pre-requisites (apt install)" 
    echo "[2].....Create kubernetes cluster (kubeadm init)" 
    echo "[3].....Deploy kubernetes network (flannel and multus)" 
    echo "-----------------------------------------------------------" 
    echo "-------------------------- TOOLS --------------------------" 
    echo "-----------------------------------------------------------" 
    echo "(unAll)..unDeploy apps and kube-network (undo step3)" 
    echo "(unApps).unDeploy apps" 
    echo "(b)......binaries installation locally (helm, kubectl, jq and k9s)" 
    echo "(k)......k9s - monitor K8s cluster status" 
    echo "(c)......copy kubeconfig file from the master node" 
    echo "(n)......network diagnostic tool (dnstools pod deployment)" 
    echo "(d)......dns fix" 
    echo "(s)......swap partition removal" 
    echo "(R)......REBOOT ALL NODES" 
    echo "(all)....installation steps at once" 
    echo "-----------------------------------------------------------" 
    read -r OPTION
  else
    OPTION="$2"
    CONTINUE=false
  fi
  
  case $OPTION in
  q) ## QUIT AND CLEAN UP
    echo "-- Cleaning up " 
    rm -rf tmp
    rm -rf logs
    rm -rf -- *.BACKUP
    rm -rf .*.BACKUP
    exit 0
    ;;
  c) ## Create kubeconfig file
    echo "-- Copying kubeconfig to kubeconfig" 
    rm -f "$KUBECONFIG"
    copyKubeconfig
    END_OF_SCRIPT
    ;;
  s) ## Remove swap partition and reboot
    echo "-- Removing SWAP" 
    SWAPRemoval
    END_OF_SCRIPT
    ;;
  b)
    echo "-- Installing binaries" 
    binInstall
    END_OF_SCRIPT
    ;;
  d)
    echo "-- Fixing DNS" 
    FixDNS
    END_OF_SCRIPT
    ;;
  k) ## k9S - Monitor K8s cluster status
    echo "-- Running k9s" 
    copyKubeconfig
    k9s -A
    END_OF_SCRIPT
    ;;
  n) ## Deploy dns tools
    echo "-- Running dnstools container" 
    runDNSTool
    END_OF_SCRIPT
    ;;
  R) ## Reboot all nodes
    echo "-- Rebooting all nodes" 
    RESTART_ALL_NODES "${NODE_ARRAY[@]}" "$PRIVATE_KEY"
    END_OF_SCRIPT
    ;;
  unApps) ## Undeploy deployment
    echo "-- Un-deploying all apps" 
    unDeployApps
    END_OF_SCRIPT
    ;;
  unAll) ## Undeploy deployment
    echo "-- Un-deploying all apps including kube-network namespace" 
    unDeployAll
    END_OF_SCRIPT
    ;;
  0)
    step0
    echo "-- Step 0 (apt uninstall) completed" 
    END_OF_SCRIPT
    ;;
  1)
    step1
    echo "-- Step 1 (apt install) completed" 
    END_OF_SCRIPT
    ;;
  2)
    step2
    echo "-- Step 2 (cluster creation) completed" 
    END_OF_SCRIPT
    ;;
  3)
    step3
    echo "-- Step 3 (network deployment) completed" 
    END_OF_SCRIPT
    ;;
  all)
    step0
    echo "-- Step 0 (apt uninstall) completed" 
    step1
    echo "-- Step 1 (apt install) completed" 
    step2
    echo "-- Step 2 (cluster creation) completed" 
    step3
    echo "-- Step 3 (network deployment) completed" 
    echo "-- Running k9s"
    k9s -A
    END_OF_SCRIPT
    ;;
  *) ## Invalid option
    echo "--?-- Invalid option" 
    sleep 1
    ;;
  esac
done
